In [1]:
%reset -f
%reload_ext autoreload
%autoreload 2

In [2]:
import os,sys
current_path = os.getcwd()
sys.path.append("/home/zhuchen/poc/scorecard")

In [3]:
name = current_path.split('/')[-1].split('_')
data = name[0]
cust = name[1]

In [4]:
print(name)

['deltaV1', 'all']

In [5]:
FILE_PATH = f'/home/zhuchen/poc/02-xyf/{data}_{cust}/file/'
DATA_PATH = f'/home/zhuchen/poc/02-xyf/{data}_{cust}/data/'
TMP_PATH  = f'/home/zhuchen/poc/02-xyf/{data}_{cust}/tmp/'
DATA_OR_PATH = '/home/zhuchen/poc/02-xyf/data_or/'

In [6]:
import gc
import pandas as pd 
import numpy as np  
import math  
import matplotlib.pyplot as plt
import copy
import zipfile
import seaborn as sns
from pylab import mpl
from ScoreCard.creat_report import Report
mpl.rcParams['font.sans-serif'] = ['SimHei']
mpl.rcParams['axes.unicode_minus'] = False  

isExists=os.path.exists(FILE_PATH)
if not isExists:
    os.makedirs(FILE_PATH) 
    
isExists=os.path.exists(DATA_PATH)
if not isExists:
    os.makedirs(DATA_PATH)

isExists=os.path.exists(TMP_PATH)
if not isExists:
    os.makedirs(TMP_PATH)  

import warnings
warnings.filterwarnings("ignore")

In [7]:
if cust == 'all':
    tag = ''
else:
    tag = '_'+cust
or_file_name = f'{data}_data_all1{tag}.parquet'

In [ ]:
if data == 'deltaV1' and cust == 'all':
    deltaV1_total_iv = pd.read_csv(f'/home/zhuchen/poc/02-xyf/data_or/deltaV1_iv.csv')
    deltaV1_total_iv.sort_values(['total_iv'],ascending=False,inplace=True)
    iv_list = deltaV1_total_iv['var_name'].to_list()[0:2000]
    data_all1 = pd.read_parquet(DATA_OR_PATH + or_file_name,columns = ['mobile', 'backPointTime', 'qudao3_act', 'label'] +iv_list)
elif data == 'deltaV1' and cust == 'api':
    deltaV1_total_iv = pd.read_csv(f'/home/zhuchen/poc/02-xyf/data_or/deltaV1_api_iv.csv')
    deltaV1_total_iv.sort_values(['total_iv'],ascending=False,inplace=True)
    iv_list = deltaV1_total_iv['var_name'].to_list()[0:3500]
    data_all1 = pd.read_parquet(DATA_OR_PATH + or_file_name,columns = ['mobile', 'backPointTime', 'qudao3_act', 'label'] +iv_list)
else:
    data_all1 = pd.read_parquet(DATA_OR_PATH + or_file_name)

In [9]:
data_all1.head()

,mobile,backPointTime,qudao3_act,label,TZ_1381_m12,TZ_1381_m24,TZ_1381_m18,TZ_0264_m15,TZ_0264_m12,TZ_0264_m18,...,TZ_0244_m4,TZ_0075_w4,TZ_0418_m8,TZ_0033_m3,TZ_0418_m9,TZ_0443_m8,TZ_0455_m3,TZ_0418_m11,TZ_0269_w4,TZ_0049_m12
0,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0
1,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0
2,f3f4e2f3c61d8f1a035a0c32987714a5,2025-02-21,API,0.0,-1.0,10.0,-1.0,1.0,1.0,1.0,...,0.0,0.000000,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0
3,6d09e74a845b0c12e86be848d40f4fd3,2025-06-09,API,0.0,20.0,20.0,20.0,35.0,35.0,35.0,...,8.0,0.916667,1.0,1.0,1.0,-1.0,3.0,1.0,0.0,0.0
4,70a24bd8e0cfa4efb16a5a26b3054bc5,2025-04-28,API,0.0,18.0,20.0,20.0,20.0,18.0,20.0,...,-1.0,0.333333,1.0,2.0,1.0,-1.0,-1.0,1.0,2.0,0.0

In [10]:
data_all1.shape

(1277742, 2004)

### 1.1 去重 & 去空

In [11]:
data_all1.shape

(1277742, 2004)

In [12]:
data_all1['label'].isnull().sum()

0

In [13]:
data_all1 = data_all1[~data_all1['label'].isnull()].reset_index(drop=True)

In [14]:
data_all1

,mobile,backPointTime,qudao3_act,label,TZ_1381_m12,TZ_1381_m24,TZ_1381_m18,TZ_0264_m15,TZ_0264_m12,TZ_0264_m18,...,TZ_0244_m4,TZ_0075_w4,TZ_0418_m8,TZ_0033_m3,TZ_0418_m9,TZ_0443_m8,TZ_0455_m3,TZ_0418_m11,TZ_0269_w4,TZ_0049_m12
0,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0
1,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0
2,f3f4e2f3c61d8f1a035a0c32987714a5,2025-02-21,API,0.0,-1.0,10.0,-1.0,1.0,1.0,1.0,...,0.0,0.000000,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0
3,6d09e74a845b0c12e86be848d40f4fd3,2025-06-09,API,0.0,20.0,20.0,20.0,35.0,35.0,35.0,...,8.0,0.916667,1.0,1.0,1.0,-1.0,3.0,1.0,0.0,0.0
4,70a24bd8e0cfa4efb16a5a26b3054bc5,2025-04-28,API,0.0,18.0,20.0,20.0,20.0,18.0,20.0,...,-1.0,0.333333,1.0,2.0,1.0,-1.0,-1.0,1.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1277737,a18e8ccd88bb61bc7f9dd825d25b8850,2024-11-13,APP自然流量,0.0,24.0,31.0,30.0,27.0,25.0,31.0,...,-1.0,0.666667,1.0,0.0,1.0,0.0,-1.0,1.0,2.0,0.0
1277738,e0c1b14d5f5953670ed63c102f3ead9f,2024-11-15,APP自然流量,0.0,-1.0,-1.0,-1.0,20.0,20.0,20.0,...,-1.0,0.000000,1.0,2.0,1.0,1.0,-1.0,1.0,-1.0,1.0
1277739,82bc32734d6acd2f8993add147648f26,2024-11-12,APP自然流量,0.0,25.0,38.0,25.0,26.0,26.0,26.0,...,0.0,0.250000,1.0,1.0,1.0,1.0,0.0,1.0,-1.0,1.0
1277740,45ed4aab69e0a3039def1ed484e79716,2024-11-23,APP自然流量,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,20.0,0.000000,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0
1277741,5875a4f00321a6577d12112d8d0b8aa8,2024-11-12,APP自然流量,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,0.000000,-1.0,0.0,-1.0,0.0,-1.0,-1.0,-1.0,0.0

In [15]:
data_all1[['mobile','backPointTime','qudao3_act']].value_counts()

mobile                            backPointTime  qudao3_act
aa2cd2b58fbd554c6bd30187ff5a2e77  2024-11-25     信息流           2
b11611521b5059ffabe19b71132a4c45  2024-11-04     信息流           2
1f96bb61f51b898a87bb547c0637920d  2025-05-19     信息流           2
c4851c5a6baec545cf67a86cd7c471df  2024-08-09     信息流           2
d7cfe754b27299180947d90b10215db4  2025-04-07     信息流           2
                                                              ..
54eb9b9b8d8a2c6d6488f00eec284d21  2025-06-19     信息流           1
54eb9a32b5c6224ca3e2e7adb38597d9  2025-01-26     信息流           1
54eb939869e2a2e00d3ac252250b616f  2025-01-13     API           1
54eb8f55a4dab82bbb2e856c83f54b7e  2024-10-02     API           1
fffffc381ac87676d9c4cad3dfc9972d  2024-09-17     APP自然流量       1
Length: 1277540, dtype: int64

In [16]:
(data_all1[['mobile','backPointTime']].value_counts() > 1).sum()

202

In [17]:
data_all1.shape

(1277742, 2004)

In [18]:
# data_all1[(data_all1['mobile_sha256'] == '8981c912918c45aa4693b8e042bf42bc6c2c8c0938931696efe1e5c99df53bc8') & (data_all1['hs_date'] == '2024-10-26')].to_csv('data_all1_2024-10-26.csv', index=False)

In [19]:
# 这一步老大的意思是可以不去重
# data_all1.drop_duplicates(['mobile_sha256','hs_date','sample_type'],inplace=True)
# data_all1.shape

In [20]:
# data_all1[['mobile_sha256','hs_date','sample_type']].value_counts()

In [21]:
# data_all1[['mobile_sha256','hs_date','sample_type']].value_counts().iloc[0]

### 1.2 数据类型转换

In [22]:
data_all1.select_dtypes(include='object')

                                   mobile backPointTime qudao3_act
0        663c8e4d4a0d11fa9767b332f30c1921    2024-08-11        信息流
1        663c8e4d4a0d11fa9767b332f30c1921    2024-08-11        信息流
2        f3f4e2f3c61d8f1a035a0c32987714a5    2025-02-21        API
3        6d09e74a845b0c12e86be848d40f4fd3    2025-06-09        API
4        70a24bd8e0cfa4efb16a5a26b3054bc5    2025-04-28        API
...                                   ...           ...        ...
1277737  a18e8ccd88bb61bc7f9dd825d25b8850    2024-11-13    APP自然流量
1277738  e0c1b14d5f5953670ed63c102f3ead9f    2024-11-15    APP自然流量
1277739  82bc32734d6acd2f8993add147648f26    2024-11-12    APP自然流量
1277740  45ed4aab69e0a3039def1ed484e79716    2024-11-23    APP自然流量
1277741  5875a4f00321a6577d12112d8d0b8aa8    2024-11-12    APP自然流量

[1277742 rows x 3 columns]

### 1.3 观察数据时间分布

In [23]:
gc.collect()

0

In [24]:
from DataPreprocessing.Datasets.Describe import badrate_by_month
# data_all1.reset_index(drop=True, inplace=True)
data_all1['target'] = 'train'

In [25]:
data_all1.head()

,mobile,backPointTime,qudao3_act,label,TZ_1381_m12,TZ_1381_m24,TZ_1381_m18,TZ_0264_m15,TZ_0264_m12,TZ_0264_m18,...,TZ_0075_w4,TZ_0418_m8,TZ_0033_m3,TZ_0418_m9,TZ_0443_m8,TZ_0455_m3,TZ_0418_m11,TZ_0269_w4,TZ_0049_m12,target
0,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0,train
1,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.250000,-1.0,0.0,-1.0,0.5,8.0,-1.0,0.0,0.0,train
2,f3f4e2f3c61d8f1a035a0c32987714a5,2025-02-21,API,0.0,-1.0,10.0,-1.0,1.0,1.0,1.0,...,0.000000,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,0.0,train
3,6d09e74a845b0c12e86be848d40f4fd3,2025-06-09,API,0.0,20.0,20.0,20.0,35.0,35.0,35.0,...,0.916667,1.0,1.0,1.0,-1.0,3.0,1.0,0.0,0.0,train
4,70a24bd8e0cfa4efb16a5a26b3054bc5,2025-04-28,API,0.0,18.0,20.0,20.0,20.0,18.0,20.0,...,0.333333,1.0,2.0,1.0,-1.0,-1.0,1.0,2.0,0.0,train

In [26]:
month_time = badrate_by_month(data_all1, 'backPointTime', ['train'], 'label')
month_time

          count     bad      good  bad_rate
2024-07  101890  3192.0   98698.0  0.031328
2024-08  111257  4113.0  107144.0  0.036968
2024-09  116716  4736.0  111980.0  0.040577
2024-10  113623  5003.0  108620.0  0.044032
2024-11  105345  4880.0  100465.0  0.046324
2024-12  107385  4970.0  102415.0  0.046282
2025-01  120569  5661.0  114908.0  0.046952
2025-02  103627  5473.0   98154.0  0.052814
2025-03  114568  6419.0  108149.0  0.056028
2025-04  109790  6019.0  103771.0  0.054823
2025-05  107435  5677.0  101758.0  0.052841
2025-06   65537  3521.0   62016.0  0.053725

In [27]:
# plt.figure(figsize=(10, 5))
# plt.plot(month_time.index, month_time['bad_rate'], linewidth=2, label='bad_rate')
# plt.title('bad_rate by month', fontsize=15)
# plt.xlabel("time", fontsize=12)
# plt.ylabel("bad_rate", fontsize=12)
# plt.tick_params(axis='both', labelsize=10)
# plt.ylim(min(month_time['bad_rate'])*0.9,max(month_time['bad_rate'])*1.1)
# plt.show()

In [28]:
from DataPreprocessing.Datasets.Describe import badrate_by_day
day_time = badrate_by_day(data_all1, 'backPointTime', ['train'], 'label')
day_time

            count    bad    good  bad_rate
2024-07-01   3397  104.0  3293.0  0.030615
2024-07-02   3351  112.0  3239.0  0.033423
2024-07-03   3514  106.0  3408.0  0.030165
2024-07-04   3504  109.0  3395.0  0.031107
2024-07-05   3739   97.0  3642.0  0.025943
...           ...    ...     ...       ...
2025-06-18   2783  161.0  2622.0  0.057851
2025-06-19   2946  167.0  2779.0  0.056687
2025-06-20   2976  161.0  2815.0  0.054099
2025-06-21   2235  108.0  2127.0  0.048322
2025-06-22   1392   94.0  1298.0  0.067529

[357 rows x 4 columns]

In [29]:
# plt.figure(figsize=(15, 5))
# plt.plot(day_time.index, day_time['bad_rate'], linewidth=2, label='bad_rate')
# plt.title('bad_rate by day', fontsize=15)
# plt.xlabel("time", fontsize=12)
# plt.ylabel("bad_rate", fontsize=12)
# plt.tick_params(axis='both', labelsize=10)
# plt.ylim(min(day_time['bad_rate'])*0.8,max(day_time['bad_rate'])*1.1)
# plt.show()

In [30]:
from DataPreprocessing.Datasets.Describe import badrate_by_week
week_time = badrate_by_week(data_all1, 'backPointTime', ['train'], 'label')
week_time

    count     bad     good  bad_rate    date_max    date_min
1   26765  1217.0  25548.0  0.045470  2025-01-05  2024-12-30
2   26004  1223.0  24781.0  0.047031  2025-01-12  2025-01-06
3   26256  1246.0  25010.0  0.047456  2025-01-19  2025-01-13
4   33055  1547.0  31508.0  0.046801  2025-01-26  2025-01-20
5   22398  1104.0  21294.0  0.049290  2025-02-02  2025-01-27
6   27266  1443.0  25823.0  0.052923  2025-02-09  2025-02-03
7   25908  1372.0  24536.0  0.052957  2025-02-16  2025-02-10
8   25281  1341.0  23940.0  0.053044  2025-02-23  2025-02-17
9   26265  1363.0  24902.0  0.051894  2025-03-02  2025-02-24
10  27990  1602.0  26388.0  0.057235  2025-03-09  2025-03-03
11  26673  1487.0  25186.0  0.055749  2025-03-16  2025-03-10
12  26163  1506.0  24657.0  0.057562  2025-03-23  2025-03-17
13  22742  1245.0  21497.0  0.054745  2025-03-30  2025-03-24
14  24356  1290.0  23066.0  0.052964  2025-04-06  2025-03-31
15  25748  1368.0  24380.0  0.053130  2025-04-13  2025-04-07
16  25945  1446.0  24499.0  0.055733  2025-04-20  2025-04-14
17  25738  1467.0  24271.0  0.056997  2025-04-27  2025-04-21
18  27521  1496.0  26025.0  0.054358  2025-05-04  2025-04-28
19  30977  1712.0  29265.0  0.055267  2025-05-11  2025-05-05
20  24036  1336.0  22700.0  0.055583  2025-05-18  2025-05-12
21  21283  1025.0  20258.0  0.048161  2025-05-25  2025-05-19
22  18233   892.0  17341.0  0.048922  2025-06-01  2025-05-26
23  23221  1220.0  22001.0  0.052539  2025-06-08  2025-06-02
24  20806  1136.0  19670.0  0.054600  2025-06-15  2025-06-09
25  18157   997.0  17160.0  0.054910  2025-06-22  2025-06-16
27  24283   727.0  23556.0  0.029939  2024-07-07  2024-07-01
28  23656   718.0  22938.0  0.030352  2024-07-14  2024-07-08
29  22565   736.0  21829.0  0.032617  2024-07-21  2024-07-15
30  21538   662.0  20876.0  0.030736  2024-07-28  2024-07-22
31  23650   819.0  22831.0  0.034630  2024-08-04  2024-07-29
32  25691   942.0  24749.0  0.036667  2024-08-11  2024-08-05
33  24562   927.0  23635.0  0.037741  2024-08-18  2024-08-12
34  25880   935.0  24945.0  0.036128  2024-08-25  2024-08-19
35  25439  1011.0  24428.0  0.039742  2024-09-01  2024-08-26
36  27320  1145.0  26175.0  0.041911  2024-09-08  2024-09-02
37  26337  1028.0  25309.0  0.039033  2024-09-15  2024-09-09
38  27229  1150.0  26079.0  0.042234  2024-09-22  2024-09-16
39  27119  1076.0  26043.0  0.039677  2024-09-29  2024-09-23
40  27108  1147.0  25961.0  0.042312  2024-10-06  2024-09-30
41  28110  1149.0  26961.0  0.040875  2024-10-13  2024-10-07
42  25273  1064.0  24209.0  0.042100  2024-10-20  2024-10-14
43  24683  1193.0  23490.0  0.048333  2024-10-27  2024-10-21
44  25289  1225.0  24064.0  0.048440  2024-11-03  2024-10-28
45  27998  1289.0  26709.0  0.046039  2024-11-10  2024-11-04
46  23890  1056.0  22834.0  0.044203  2024-11-17  2024-11-11
47  22507  1009.0  21498.0  0.044830  2024-11-24  2024-11-18
48  22195  1097.0  21098.0  0.049426  2024-12-01  2024-11-25
49  25226  1217.0  24009.0  0.048244  2024-12-08  2024-12-02
50  23203  1056.0  22147.0  0.045511  2024-12-15  2024-12-09
51  24850  1152.0  23698.0  0.046358  2024-12-22  2024-12-16
52  23354  1053.0  22301.0  0.045089  2024-12-29  2024-12-23

In [31]:
# plt.figure(figsize=(15, 5))
# plt.plot(week_time.index, week_time['bad_rate'], linewidth=2, label='bad_rate')
# plt.title('bad_rate by week', fontsize=15)
# plt.xlabel("time", fontsize=12)
# plt.ylabel("bad_rate", fontsize=12)
# plt.tick_params(axis='both', labelsize=10)
# plt.ylim(0,max(week_time['bad_rate'])*1.1)
# plt.show()

### 1.4 分割数据集

In [32]:
data_all1.head()

,mobile,backPointTime,qudao3_act,label,TZ_1381_m12,TZ_1381_m24,TZ_1381_m18,TZ_0264_m15,TZ_0264_m12,TZ_0264_m18,...,TZ_0418_m9,TZ_0443_m8,TZ_0455_m3,TZ_0418_m11,TZ_0269_w4,TZ_0049_m12,target,month_time,day_time,week_time
0,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.0,0.5,8.0,-1.0,0.0,0.0,train,2024-08,2024-08-11,32
1,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.0,0.5,8.0,-1.0,0.0,0.0,train,2024-08,2024-08-11,32
2,f3f4e2f3c61d8f1a035a0c32987714a5,2025-02-21,API,0.0,-1.0,10.0,-1.0,1.0,1.0,1.0,...,-1.0,-1.0,0.0,-1.0,-1.0,0.0,train,2025-02,2025-02-21,8
3,6d09e74a845b0c12e86be848d40f4fd3,2025-06-09,API,0.0,20.0,20.0,20.0,35.0,35.0,35.0,...,1.0,-1.0,3.0,1.0,0.0,0.0,train,2025-06,2025-06-09,24
4,70a24bd8e0cfa4efb16a5a26b3054bc5,2025-04-28,API,0.0,18.0,20.0,20.0,20.0,18.0,20.0,...,1.0,-1.0,-1.0,1.0,2.0,0.0,train,2025-04,2025-04-28,18

In [33]:
data_all1['weight'] = 1
data_all1['target'] = 'train'

In [ ]:
# 最后10%为oot
data_all1.loc[(pd.to_datetime(data_all1['backPointTime']) >= pd.to_datetime(data_all1['backPointTime']).quantile(0.9)) & (data_all1['target'] =='train'),'target'] = 'oot'

In [35]:
# data_all1.loc[((data_all1['stage']) == 'test') & (data_all1['target'] =='train'),'target'] = 'oot'

In [36]:
data_all1['target'].value_counts()

train    1148251
oot       129491
Name: target, dtype: int64

In [37]:
data_all1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1277742 entries, 0 to 1277741
Columns: 2009 entries, mobile to weight
dtypes: float32(2000), float64(1), int64(2), object(6)
memory usage: 9.6+ GB

In [38]:
gc.collect()

0

In [39]:
from DataPreprocessing.Datasets.Split import by_stratify
data_all1, res = by_stratify(data_all1, 0.3, 2025, date='backPointTime', dep='label')

         count  bad_rate      bad    time_min    time_max
all    1277742  0.046695  59664.0  2024-07-01  2025-06-22
train   803775  0.046010  36982.0  2024-07-01  2025-05-10
valid   344476  0.046009  15849.0  2024-07-01  2025-05-10
oot     129491  0.052768   6833.0  2025-05-11  2025-06-22
ratio_bad_good:  0.04822944393076097
train    803775
valid    344476
oot      129491
Name: target, dtype: int64

In [40]:
data_all1.head()

,mobile,backPointTime,qudao3_act,label,TZ_1381_m12,TZ_1381_m24,TZ_1381_m18,TZ_0264_m15,TZ_0264_m12,TZ_0264_m18,...,TZ_0443_m8,TZ_0455_m3,TZ_0418_m11,TZ_0269_w4,TZ_0049_m12,target,month_time,day_time,week_time,weight
0,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.5,8.0,-1.0,0.0,0.0,valid,2024-08,2024-08-11,32,1
1,663c8e4d4a0d11fa9767b332f30c1921,2024-08-11,信息流,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.5,8.0,-1.0,0.0,0.0,train,2024-08,2024-08-11,32,1
2,f3f4e2f3c61d8f1a035a0c32987714a5,2025-02-21,API,0.0,-1.0,10.0,-1.0,1.0,1.0,1.0,...,-1.0,0.0,-1.0,-1.0,0.0,valid,2025-02,2025-02-21,8,1
3,6d09e74a845b0c12e86be848d40f4fd3,2025-06-09,API,0.0,20.0,20.0,20.0,35.0,35.0,35.0,...,-1.0,3.0,1.0,0.0,0.0,oot,2025-06,2025-06-09,24,1
4,70a24bd8e0cfa4efb16a5a26b3054bc5,2025-04-28,API,0.0,18.0,20.0,20.0,20.0,18.0,20.0,...,-1.0,-1.0,1.0,2.0,0.0,train,2025-04,2025-04-28,18,1

In [41]:
res

         count  bad_rate      bad    time_min    time_max
all    1277742  0.046695  59664.0  2024-07-01  2025-06-22
train   803775  0.046010  36982.0  2024-07-01  2025-05-10
valid   344476  0.046009  15849.0  2024-07-01  2025-05-10
oot     129491  0.052768   6833.0  2025-05-11  2025-06-22

In [127]:
# data_all1.to_pickle(DATA_PATH + 'data_model.pkl')
# data_all1.to_pickle(DATA_PATH + 'data_model.zip', compression='zip')

In [42]:
data_all1.to_parquet(DATA_PATH + 'data_model.parquet')

### 1.5 数据分析

In [77]:
# data_all1 = pd.read_parquet(DATA_PATH + 'data_model.parquet')

In [43]:
ex_lst = ['mobile','backPointTime','qudao3_act','label',
 'weight',
 'target',
 'month_time',
 'day_time',
 'week_time',]
ft_lst = [i for i in data_all1.columns if i not in ex_lst]
len(ft_lst)

2000

In [44]:
print(ft_lst)

['TZ_1381_m12', 'TZ_1381_m24', 'TZ_1381_m18', 'TZ_0264_m15', 'TZ_0264_m12', 'TZ_0264_m18', 'TZ_0264_m24', 'TZ_0266_m24', 'TZ_0266_m15', 'TZ_0266_m18', 'TZ_0266_m12', 'TZ_0266_m9', 'TZ_0264_m9', 'TZ_0272_m24', 'TZ_0326_m24', 'TZ_0080_m24', 'TZ_0454_m24', 'TZ_0083_m24', 'TZ_1381_m6', 'TZ_0265_m15', 'TZ_0267_m24', 'TZ_0324_m24', 'TZ_0265_m18', 'TZ_0265_m24', 'TZ_0265_m12', 'TZ_0266_m6', 'TZ_0267_m18', 'TZ_0081_m24', 'TZ_1317_m24', 'TZ_0272_m18', 'TZ_0274_m24', 'TZ_0266_m5', 'TZ_0272_m15', 'TZ_0265_m9', 'TZ_0080_m18', 'TZ_0326_m18', 'TZ_0083_m18', 'TZ_0264_m6', 'TZ_0080_m15', 'TZ_0325_m24', 'TZ_0267_m15', 'TZ_1317_m18', 'TZ_0083_m15', 'TZ_0324_m18', 'TZ_0326_m15', 'TZ_1317_m12', 'TZ_0267_m12', 'TZ_0273_m24', 'TZ_0081_m18', 'TZ_0267_m9', 'TZ_0080_m12', 'TZ_0324_m15', 'TZ_0083_m12', 'TZ_0272_m12', 'TZ_0081_m15', 'TZ_0264_m5', 'TZ_0274_m18', 'TZ_0266_m4', 'TZ_0265_m6', 'TZ_0454_m12', 'TZ_0274_m15', 'TZ_0081_m12', 'TZ_0326_m12', 'TZ_0327_m24', 'TZ_0325_m18', 'TZ_0273_m18', 'TZ_0324_m12', 'TZ_0273_m15', 'TZ_1349_m24', 'TZ_0274_m12', 'TZ_0325_m15', 'TZ_0265_m5', 'TZ_0272_m9', 'TZ_0264_m4', 'TZ_0270_m24', 'TZ_0273_m12', 'TZ_0135_m24', 'TZ_0132_m24', 'TZ_0080_m9', 'TZ_0083_m9', 'TZ_0195_m24', 'TZ_1349_m18', 'TZ_0267_m6', 'TZ_0081_m9', 'TZ_0275_m24', 'TZ_0268_m24', 'TZ_0266_m3', 'TZ_1397_m24', 'TZ_1541_m24', 'TZ_0274_m9', 'TZ_0326_m9', 'TZ_0270_m18', 'TZ_0072_m24', 'TZ_0265_m4', 'TZ_1349_m12', 'TZ_0133_m24', 'TZ_0324_m9', 'TZ_0325_m12', 'TZ_0327_m18', 'TZ_1333_m24', 'TZ_1397_m18', 'TZ_1557_m24', 'TZ_0135_m18', 'TZ_0193_m24', 'TZ_0273_m9', 'TZ_0267_m5', 'TZ_0192_m24', 'TZ_1525_m24', 'TZ_0132_m18', 'TZ_1397_m12', 'TZ_1333_m18', 'TZ_0195_m18', 'TZ_0135_m15', 'TZ_0270_m15', 'TZ_1381_m3', 'TZ_1528_m24', 'TZ_1317_m6', 'TZ_0275_m18', 'TZ_0132_m15', 'TZ_0133_m18', 'TZ_0264_m3', 'TZ_1558_m24', 'TZ_0961_m24', 'TZ_1573_m24', 'TZ_1333_m12', 'TZ_1557_m18', 'TZ_0133_m15', 'TZ_1526_m24', 'TZ_0327_m15', 'TZ_1365_m24', 'TZ_0270_m12', 'TZ_0193_m18', 'TZ_0330_m24', 'TZ_1525_m18', 'TZ_0192_m18', 'TZ_1541_m18', 'TZ_0268_m18', 'TZ_1560_m24', 'TZ_0325_m9', 'TZ_0132_m12', 'TZ_0072_m18', 'TZ_0195_m15', 'TZ_1509_m24', 'TZ_1528_m18', 'TZ_0135_m12', 'TZ_0275_m15', 'TZ_0193_m15', 'TZ_0265_m3', 'TZ_1365_m18', 'TZ_1524_m24', 'TZ_0268_m15', 'TZ_0454_m6', 'TZ_0133_m12', 'TZ_1589_m24', 'TZ_0272_m6', 'TZ_1365_m12', 'TZ_0267_m4', 'TZ_0326_m6', 'TZ_0080_m6', 'TZ_1560_m18', 'TZ_0328_m24', 'TZ_1556_m24', 'TZ_0961_m18', 'TZ_0081_m6', 'TZ_0327_m12', 'TZ_1590_m24', 'TZ_0192_m15', 'TZ_0075_m24', 'TZ_0132_m9', 'TZ_0083_m6', 'TZ_0072_m15', 'TZ_0324_m6', 'TZ_0195_m12', 'TZ_0193_m12', 'TZ_0135_m9', 'TZ_0183_m24', 'TZ_1558_m18', 'TZ_0271_m24', 'TZ_0270_m9', 'TZ_0133_m9', 'TZ_0139_m24', 'TZ_0136_m24', 'TZ_0266_m2', 'TZ_0274_m6', 'TZ_1509_m18', 'TZ_1349_m6', 'TZ_0330_m18', 'TZ_1592_m24', 'TZ_1557_m12', 'TZ_1525_m12', 'TZ_0332_m24', 'TZ_0268_m12', 'TZ_0192_m12', 'TZ_0140_m24', 'TZ_0143_m24', 'TZ_0272_m5', 'TZ_0192_m9', 'TZ_1588_m24', 'TZ_1397_m6', 'TZ_1524_m18', 'TZ_0273_m6', 'TZ_0325_m6', 'TZ_0073_m24', 'TZ_1573_m18', 'TZ_1528_m12', 'TZ_0193_m9', 'TZ_0276_m24', 'TZ_0275_m12', 'TZ_1526_m18', 'TZ_0334_m24', 'TZ_0961_m12', 'TZ_1556_m18', 'TZ_0087_m24', 'TZ_0084_m24', 'TZ_0326_m5', 'TZ_0080_m5', 'TZ_0137_m24', 'TZ_0330_m15', 'TZ_0375', 'TZ_1589_m18', 'TZ_0333_m24', 'TZ_0072_m12', 'TZ_0264_m2', 'TZ_1560_m12', 'TZ_0141_m24', 'TZ_0195_m9', 'TZ_0136_m18', 'TZ_0139_m18', 'TZ_1541_m12', 'TZ_0324_m5', 'TZ_0076_m24', 'TZ_1524_m12', 'TZ_0083_m5', 'TZ_1590_m18', 'TZ_0327_m9', 'TZ_0274_m5', 'TZ_0132_m6', 'TZ_0278_m24', 'TZ_0328_m18', 'TZ_0265_m2', 'TZ_0139_m15', 'TZ_0135_m6', 'TZ_0277_m24', 'TZ_0075_m18', 'TZ_0085_m24', 'TZ_0136_m15', 'TZ_1592_m18', 'TZ_0133_m6', 'TZ_0267_m3', 'TZ_0269_m24', 'TZ_0273_m5', 'TZ_1400_m24', 'TZ_0961_m9', 'TZ_0329_m24', 'TZ_0271_m18', 'TZ_1557_m6', 'TZ_1333_m6', 'TZ_1981_m24', 'TZ_1525_m6', 'TZ_1556_m12', 'TZ_0137_m18', 'TZ_1989', 'TZ_0081_m5', 'TZ_0331_m24', 'TZ_0246_m24', 'TZ_0192_m6', 'TZ_0330_m12', 'TZ_0137_m15', 'TZ_1560_m6', 'TZ_0075_m15', 'TZ_1509_m12', 'TZ_1365_m6', 'TZ_0181_m24', 'TZ_0325_m5', 'TZ_1984_m24', 'TZ_1526_m12', 'TZ_1558_m12', 'TZ_1523_m24', 'TZ_1554_m24', 'TZ_1552_m24', 'TZ_1518_m24', 'TZ_1513_m24', 'TZ_1555_m24', 'TZ_1521_m24', 'TZ_1514_m24', 'TZ_1551_m24', 'TZ_1515_m24', 'TZ_1516_m24', 'TZ_1517_m24', 'TZ_1550_m24', 'TZ_1519_m24', 'TZ_1527_m24', 'TZ_1520_m24', 'TZ_1545_m24', 'TZ_1548_m24', 'TZ_1522_m24', 'TZ_1547_m24', 'TZ_1546_m24', 'TZ_1553_m24', 'TZ_1549_m24', 'TZ_1559_m24', 'TZ_1528_m6', 'TZ_0073_m18', 'TZ_1981_m18', 'TZ_0132_m5', 'TZ_0461_m24', 'TZ_0032_m24', 'TZ_0270_m6', 'TZ_0328_m15', 'TZ_0269_m18', 'TZ_0136_m12', 'TZ_0087_m18', 'TZ_0139_m12', 'TZ_1588_m18', 'TZ_0133_m5', 'TZ_0332_m18', 'TZ_0175_m24', 'TZ_0193_m6', 'TZ_0143_m18', 'TZ_0180_m24', 'TZ_0140_m18', 'TZ_0455_m24', 'TZ_0137_m12', 'TZ_0073_m15', 'TZ_0192_m5', 'TZ_0326_m4', 'TZ_0272_m4', 'TZ_0268_m9', 'TZ_0278_m18', 'TZ_0328_m12', 'TZ_0275_m9', 'TZ_0330_m9', 'TZ_1984_m18', 'TZ_0135_m5', 'TZ_0183_m18', 'TZ_0277_m18', 'TZ_0080_m4', 'TZ_0269_m15', 'TZ_0244_m24', 'TZ_1400_m18', 'TZ_0276_m18', 'TZ_0084_m18', 'TZ_0085_m18', 'TZ_0329_m18', 'TZ_1547_m18', 'TZ_1546_m18', 'TZ_1545_m18', 'TZ_1514_m18', 'TZ_1548_m18', 'TZ_1516_m18', 'TZ_1549_m18', 'TZ_1517_m18', 'TZ_1554_m18', 'TZ_1518_m18', 'TZ_1520_m18', 'TZ_1519_m18', 'TZ_1521_m18', 'TZ_1527_m18', 'TZ_1515_m18', 'TZ_1513_m18', 'TZ_1523_m18', 'TZ_1559_m18', 'TZ_1550_m18', 'TZ_1551_m18', 'TZ_1555_m18', 'TZ_1552_m18', 'TZ_1553_m18', 'TZ_1522_m18', 'TZ_0334_m18', 'TZ_1581_m24', 'TZ_1577_m24', 'TZ_1582_m24', 'TZ_1578_m24', 'TZ_1583_m24', 'TZ_1584_m24', 'TZ_1585_m24', 'TZ_1586_m24', 'TZ_1579_m24', 'TZ_1591_m24', 'TZ_1587_m24', 'TZ_1580_m24', 'TZ_0333_m18', 'TZ_0072_m9', 'TZ_0035_m24', 'TZ_0195_m6', 'TZ_0141_m18', 'TZ_1237_m24', 'TZ_0271_m15', 'TZ_0075_m12', 'TZ_0139_m9', 'TZ_1269_m24', 'TZ_1981_m12', 'TZ_0245_m24', 'TZ_1368_m24', 'TZ_0332_m15', 'TZ_0193_m5', 'TZ_0136_m9', 'TZ_1558_m6', 'TZ_1526_m6', 'TZ_0961_m6', 'TZ_0274_m4', 'TZ_1336_m24', 'TZ_0143_m15', 'TZ_0132_m4', 'TZ_0140_m15', 'TZ_1400_m12', 'TZ_0324_m4', 'TZ_0083_m4', 'TZ_0073_m12', 'TZ_0137_m9', 'TZ_0076_m18', 'TZ_0172_m24', 'TZ_1541_m6', 'TZ_0273_m4', 'TZ_0329_m15', 'TZ_0180_m18', 'TZ_1605_m24', 'TZ_0276_m15', 'TZ_0278_m15', 'TZ_0085_m15', 'TZ_0084_m15', 'TZ_0277_m15', 'TZ_0087_m15', 'TZ_0133_m4', 'TZ_0270_m5', 'TZ_1509_m6', 'TZ_0192_m4', 'TZ_0325_m4', 'TZ_0181_m18', 'TZ_0334_m15', 'TZ_1317_m3', 'TZ_1984_m12', 'TZ_1589_m12', 'TZ_0333_m15', 'TZ_0081_m4', 'TZ_1520_m12', 'TZ_1550_m12', 'TZ_1518_m12', 'TZ_1516_m12', 'TZ_1559_m12', 'TZ_1515_m12', 'TZ_1527_m12', 'TZ_1549_m12', 'TZ_1547_m12', 'TZ_1551_m12', 'TZ_1517_m12', 'TZ_1513_m12', 'TZ_1546_m12', 'TZ_1519_m12', 'TZ_1554_m12', 'TZ_1552_m12', 'TZ_1521_m12', 'TZ_1545_m12', 'TZ_1523_m12', 'TZ_1522_m12', 'TZ_1555_m12', 'TZ_1514_m12', 'TZ_1548_m12', 'TZ_1553_m12', 'TZ_0087_m12', 'TZ_0141_m15', 'TZ_0085_m12', 'TZ_0084_m12', 'TZ_0277_m12', 'TZ_0278_m12', 'TZ_0276_m12', 'TZ_0079_m24', 'TZ_0331_m18', 'TZ_0328_m9', 'TZ_1524_m6', 'TZ_0269_m12', 'TZ_1592_m12', 'TZ_1556_m6', 'TZ_0246_m18', 'TZ_0032_m18', 'TZ_1981_m6', 'TZ_1272_m24', 'TZ_1368_m18', 'TZ_0175_m18', 'TZ_0271_m12', 'TZ_0327_m6', 'TZ_0332_m12', 'TZ_0036_m24', 'TZ_1582_m18', 'TZ_1579_m18', 'TZ_1578_m18', 'TZ_1584_m18', 'TZ_1577_m18', 'TZ_1581_m18', 'TZ_1587_m18', 'TZ_1585_m18', 'TZ_1586_m18', 'TZ_1591_m18', 'TZ_1583_m18', 'TZ_1580_m18', 'TZ_0181_m15', 'TZ_1237_m18', 'TZ_1349_m3', 'TZ_1240_m24', 'TZ_0193_m4', 'TZ_1336_m18', 'TZ_0136_m6', 'TZ_1269_m18', 'TZ_0403_m24', 'TZ_0400_m24', 'TZ_0183_m15', 'TZ_0073_m9', 'TZ_1588_m12', 'TZ_0076_m15', 'TZ_1573_m12', 'TZ_0195_m5', 'TZ_1590_m12', 'TZ_0137_m6', 'TZ_0135_m4', 'TZ_0271_m9', 'TZ_0039_m24', 'TZ_0035_m18', 'TZ_1637_m24', 'TZ_0139_m6', 'TZ_0329_m12', 'TZ_0333_m12', 'TZ_0334_m12', 'TZ_0141_m12', 'TZ_0140_m12', 'TZ_0143_m12', 'TZ_0331_m15', 'TZ_0180_m15', 'TZ_0075_m9', 'TZ_0272_m3', 'TZ_0244_m18', 'TZ_0246_m15', 'TZ_0080_m3', 'TZ_0192_m3', 'TZ_1605_m18', 'TZ_0454_m3', 'TZ_0245_m18', 'TZ_0270_m4', 'TZ_0326_m3', 'TZ_0132_m3', 'TZ_1560_m3', 'TZ_1557_m3', 'TZ_0274_m3', 'TZ_0087_m9', 'TZ_0276_m9', 'TZ_0085_m9', 'TZ_0278_m9', 'TZ_0084_m9', 'TZ_0277_m9', 'TZ_0172_m18', 'TZ_1272_m18', 'TZ_0077_m24', 'TZ_0327_m5', 'TZ_1525_m3', 'TZ_1528_m3', 'TZ_1516_m6', 'TZ_1545_m6', 'TZ_1517_m6', 'TZ_1551_m6', 'TZ_1523_m6', 'TZ_1513_m6', 'TZ_1527_m6', 'TZ_1547_m6', 'TZ_1521_m6', 'TZ_1550_m6', 'TZ_1984_m6', 'TZ_1553_m6', 'TZ_1522_m6', 'TZ_1555_m6', 'TZ_1554_m6', 'TZ_1520_m6', 'TZ_1519_m6', 'TZ_1559_m6', 'TZ_1514_m6', 'TZ_1546_m6', 'TZ_1552_m6', 'TZ_1515_m6', 'TZ_1518_m6', 'TZ_1548_m6', 'TZ_1549_m6', 'TZ_1368_m12', 'TZ_0181_m12', 'TZ_0330_m6', 'TZ_0136_m5', 'TZ_0273_m3', 'TZ_0267_m2', 'TZ_0137_m5', 'TZ_0033_m24', 'TZ_1397_m3', 'TZ_0325_m3', 'TZ_0032_m15', 'TZ_1253_m24', 'TZ_1653_m24', 'TZ_1336_m12', 'TZ_1669_m24', 'TZ_0072_m6', 'TZ_1621_m24', 'TZ_0133_m3', 'TZ_1268_m24', 'TZ_0329_m9', 'TZ_0269_m9', 'TZ_0193_m3', 'TZ_1733_m24', 'TZ_0081_m3', 'TZ_0331_m12', 'TZ_0244_m15', 'TZ_0076_m12', 'TZ_0175_m15', 'TZ_0139_m5', 'TZ_0324_m3', 'TZ_0335_m24', 'TZ_0268_m6', 'TZ_0183_m12', 'TZ_1238_m24', 'TZ_1365_m3', 'TZ_1270_m24', 'TZ_1236_m24', 'TZ_0180_m12', 'TZ_1669_m18', 'TZ_1240_m18', 'TZ_0173_m24', 'TZ_0246_m12', 'TZ_1592_m6', 'TZ_1400_m6', 'TZ_1333_m3', 'TZ_0245_m15', 'TZ_0079_m18', 'TZ_0035_m15', 'TZ_1637_m18', 'TZ_0083_m3', 'TZ_0271_m6', 'TZ_1583_m12', 'TZ_1580_m12', 'TZ_1577_m12', 'TZ_1584_m12', 'TZ_1582_m12', 'TZ_1591_m12', 'TZ_1578_m12', 'TZ_1581_m12', 'TZ_1585_m12', 'TZ_1579_m12', 'TZ_1586_m12', 'TZ_1587_m12', 'TZ_0275_m6', 'TZ_1589_m6', 'TZ_1398_m24', 'TZ_1396_m24', 'TZ_1605_m12', 'TZ_0136_m4', 'TZ_1364_m24', 'TZ_0036_m18', 'TZ_1398_m18', 'TZ_1590_m6', 'TZ_1653_m18', 'TZ_0033_m18', 'TZ_0140_m9', 'TZ_0141_m9', 'TZ_0332_m9', 'TZ_0334_m9', 'TZ_0333_m9', 'TZ_0143_m9', 'TZ_0172_m15', 'TZ_1574_m24', 'TZ_0195_m4', 'TZ_0039_m18', 'TZ_0961_m3', 'TZ_1334_m18', 'TZ_0180_m9', 'TZ_0072_m5', 'TZ_0075_m6', 'TZ_0328_m6', 'TZ_1332_m24', 'TZ_0181_m9', 'TZ_0455_m12', 'TZ_0073_m6', 'TZ_0152_m24', 'TZ_1669_m12', 'TZ_0173_m18', 'TZ_1396_m18', 'TZ_1270_m18', 'TZ_1238_m18', 'TZ_0077_m18', 'TZ_1637_m12', 'TZ_0419_m24', 'TZ_1334_m24', 'TZ_0137_m4', 'TZ_1398_m12', 'TZ_1221_m24', 'TZ_0244_m12', 'TZ_1541_m3', 'TZ_1621_m18', 'TZ_1236_m18', 'TZ_0079_m15', 'TZ_0330_m5', 'TZ_0327_m4', 'TZ_1576_m12', 'TZ_0370', 'TZ_0278_m6', 'TZ_0276_m6', 'TZ_0084_m6', 'TZ_0277_m6', 'TZ_0085_m6', 'TZ_0037_m24', 'TZ_1268_m18', 'TZ_1576_m24', 'TZ_0271_m5', 'TZ_1653_m12', 'TZ_0073_m5', 'TZ_0087_m6', 'TZ_0270_m3', 'TZ_0075_m5', 'TZ_0268_m5', 'TZ_0139_m4', 'TZ_1978_m24', 'TZ_1267_m24', 'TZ_1263_m24', 'TZ_1231_m24', 'TZ_1235_m24', 'TZ_0331_m9', 'TZ_0135_m3', 'TZ_0245_m12', 'TZ_0279_m24', 'TZ_0077_m15', 'TZ_1983_m24', 'TZ_0329_m6', 'TZ_0269_m6', 'TZ_1364_m18', 'TZ_1332_m18', 'TZ_1368_m6', 'TZ_1576_m18', 'TZ_1366_m24', 'TZ_0036_m15', 'TZ_1253_m18', 'TZ_0175_m12', 'TZ_0403_m12', 'TZ_1986', 'TZ_0136_m3', 'TZ_0032_m12', 'TZ_0461_m12', 'TZ_1269_m12', 'TZ_0076_m9', 'TZ_0173_m15', 'TZ_1237_m12', 'TZ_0264_m1', 'TZ_1588_m6', 'TZ_1226_m24', 'TZ_1259_m24', 'TZ_1262_m24', 'TZ_1258_m24', 'TZ_1264_m24', 'TZ_1232_m24', 'TZ_1233_m24', 'TZ_1230_m24', 'TZ_1271_m24', 'TZ_1234_m24', 'TZ_1225_m24', 'TZ_1266_m24', 'TZ_1227_m24', 'TZ_1261_m24', 'TZ_1228_m24', 'TZ_1257_m24', 'TZ_1260_m24', 'TZ_1265_m24', 'TZ_1229_m24', 'TZ_1239_m24', 'TZ_0132_m2', 'TZ_0275_m5', 'TZ_0133_m2', 'TZ_0033_m15', 'TZ_0328_m5', 'TZ_0079_m12', 'TZ_0192_m2', 'TZ_0264_w4', 'TZ_1559_m3', 'TZ_1522_m3', 'TZ_1549_m3', 'TZ_1546_m3', 'TZ_1526_m3', 'TZ_1556_m3', 'TZ_1515_m3', 'TZ_1553_m3', 'TZ_1516_m3', 'TZ_1513_m3', 'TZ_1547_m3', 'TZ_1554_m3', 'TZ_1527_m3', 'TZ_1555_m3', 'TZ_1521_m3', 'TZ_1519_m3', 'TZ_1551_m3', 'TZ_1514_m3', 'TZ_1981_m3', 'TZ_1550_m3', 'TZ_1523_m3', 'TZ_1548_m3', 'TZ_1984_m3', 'TZ_1517_m3', 'TZ_1524_m3', 'TZ_1558_m3', 'TZ_1520_m3', 'TZ_1545_m3', 'TZ_1552_m3', 'TZ_1518_m3', 'TZ_1263_m18', 'TZ_1267_m18', 'TZ_1231_m18', 'TZ_1235_m18', 'TZ_0247_m24', 'TZ_0193_m2', 'TZ_0266_w4', 'TZ_0035_m12', 'TZ_0072_m4', 'TZ_1978_m18', 'TZ_0039_m15', 'TZ_0077_m12', 'TZ_1542_m24', 'TZ_0277_m5', 'TZ_0084_m5', 'TZ_0085_m5', 'TZ_0278_m5', 'TZ_0276_m5', 'TZ_0137_m3', 'TZ_1983_m18', 'TZ_0416_m24', 'TZ_0246_m9', 'TZ_1261_m18', 'TZ_1233_m18', 'TZ_1234_m18', 'TZ_1257_m18', 'TZ_1258_m18', 'TZ_1262_m18', 'TZ_1259_m18', 'TZ_1225_m18', 'TZ_1226_m18', 'TZ_1227_m18', 'TZ_1230_m18', 'TZ_1239_m18', 'TZ_1260_m18', 'TZ_1265_m18', 'TZ_1229_m18', 'TZ_1271_m18', 'TZ_1264_m18', 'TZ_1228_m18', 'TZ_1232_m18', 'TZ_1266_m18', 'TZ_0087_m5', 'TZ_0334_m6', 'TZ_0140_m6', 'TZ_0332_m6', 'TZ_0333_m6', 'TZ_0141_m6', 'TZ_1621_m12', 'TZ_0183_m9', 'TZ_0143_m6', 'TZ_0176_m24', 'TZ_0335_m18', 'TZ_0172_m12', 'TZ_0073_m4', 'TZ_1332_m12', 'TZ_0037_m18', 'TZ_0180_m6', 'TZ_0268_m4', 'TZ_0403_m11', 'TZ_1366_m18', 'TZ_1582_m6', 'TZ_1587_m6', 'TZ_1591_m6', 'TZ_1577_m6', 'TZ_1578_m6', 'TZ_1586_m6', 'TZ_1579_m6', 'TZ_1580_m6', 'TZ_1584_m6', 'TZ_1581_m6', 'TZ_1583_m6', 'TZ_1585_m6', 'TZ_0269_m5', 'TZ_1396_m12', 'TZ_0155_m24', 'TZ_0075_m4', 'TZ_1334_m12', 'TZ_0252_m24', 'TZ_0330_m4', 'TZ_1221_m18', 'TZ_0179_m24', 'TZ_1509_m3', 'TZ_0272_m2', 'TZ_0274_m2', 'TZ_0081_m2', 'TZ_0080_m2', 'TZ_0273_m2', 'TZ_0180_m5', 'TZ_0329_m5', 'TZ_1573_m6', 'TZ_1510_m24', 'TZ_1336_m6', 'TZ_1382_m24', 'TZ_0271_m4', 'TZ_0265_m1', 'TZ_1272_m12', 'TZ_0277_m4', 'TZ_0084_m4', 'TZ_0085_m4', 'TZ_0276_m4', 'TZ_0278_m4', 'TZ_0326_m2', 'TZ_0963_m24', 'TZ_1398_m6', 'TZ_1240_m12', 'TZ_1366_m12', 'TZ_0400_m12', 'TZ_0265_w4', 'TZ_0250_m24', 'TZ_1364_m12', 'TZ_0077_m9', 'TZ_0181_m6', 'TZ_1544_m24', 'TZ_1544_m18', 'TZ_0335_m15', 'TZ_0403_m10', 'TZ_0032_m9', 'TZ_0270_m2', 'TZ_0087_m4', 'TZ_0173_m12', 'TZ_0052_m24', 'TZ_1544_m12', 'TZ_0275_m4', 'TZ_0269_m4', 'TZ_0036_m12', 'TZ_0037_m15', 'TZ_0333_m5', 'TZ_0140_m5', 'TZ_0141_m5', 'TZ_0332_m5', 'TZ_0334_m5', 'TZ_0033_m12', 'TZ_0253_m24', 'TZ_0181_m5', 'TZ_0175_m9', 'TZ_1656_m24', 'TZ_0079_m9', 'TZ_1400_m3', 'TZ_1990', 'TZ_0143_m5', 'TZ_0136_m2', 'TZ_0245_m9', 'TZ_0073_m3', 'TZ_1624_m24', 'TZ_0072_m3', 'TZ_0145_m24', 'TZ_0338_m24', 'TZ_0144_m24', 'TZ_0337_m24', 'TZ_0147_m24', 'TZ_0336_m24', 'TZ_0195_m3', 'TZ_0139_m3', 'TZ_1733_m18', 'TZ_0327_m3', 'TZ_0172_m9', 'TZ_0324_m2', 'TZ_0403_m9', 'TZ_0039_m12', 'TZ_0061_m24', 'TZ_0254_m24', 'TZ_0060_m24', 'TZ_0063_m24', 'TZ_0244_m9', 'TZ_0137_m2', 'TZ_0035_m9', 'TZ_0325_m2', 'TZ_0328_m4', 'TZ_0400_m11', 'TZ_0331_m6', 'TZ_1385_m24', 'TZ_1399_m24', 'TZ_1394_m24', 'TZ_1392_m24', 'TZ_1389_m24', 'TZ_1387_m24', 'TZ_1393_m24', 'TZ_1386_m24', 'TZ_1395_m24', 'TZ_1390_m24', 'TZ_1388_m24', 'TZ_1391_m24', 'TZ_1236_m12', 'TZ_1388_m18', 'TZ_1391_m18', 'TZ_1392_m18', 'TZ_1390_m18', 'TZ_1395_m18', 'TZ_1394_m18', 'TZ_1385_m18', 'TZ_1399_m18', 'TZ_1386_m18', 'TZ_1393_m18', 'TZ_1389_m18', 'TZ_1387_m18', 'TZ_1268_m12', 'TZ_0177_m24', 'TZ_0076_m6', 'TZ_0963_m18', 'TZ_0153_m24', 'TZ_0250_m18', 'TZ_0329_m4', 'TZ_0224_m24', 'TZ_0403_m8', 'TZ_1574_m18', 'TZ_1368_m3', 'TZ_1979_m18', 'TZ_1334_m6', 'TZ_1654_m24', 'TZ_0180_m4', 'TZ_0335_m12', 'TZ_1395_m12', 'TZ_1387_m12', 'TZ_1386_m12', 'TZ_1391_m12', 'TZ_1388_m12', 'TZ_1394_m12', 'TZ_1392_m12', 'TZ_1399_m12', 'TZ_1389_m12', 'TZ_1385_m12', 'TZ_1393_m12', 'TZ_1390_m12', 'TZ_0055_m24', 'TZ_0400_m10', 'TZ_1979_m24', 'TZ_0247_m18', 'TZ_1270_m12', 'TZ_1238_m12', 'TZ_1592_m3', 'TZ_0176_m18', 'TZ_0268_m3', 'TZ_0052_m18', 'TZ_1253_m12', 'TZ_0181_m4', 'TZ_1396_m6', 'TZ_0404_m24', 'TZ_0330_m3', 'TZ_1267_m12', 'TZ_1263_m12', 'TZ_1231_m12', 'TZ_1235_m12', 'TZ_1987', 'TZ_0403_m7', 'TZ_1979_m12', 'TZ_1978_m12', 'TZ_1983_m12', 'TZ_1542_m18', 'TZ_0083_m2', 'TZ_1620_m24', 'TZ_0179_m18', 'TZ_1265_m12', 'TZ_1227_m12', 'TZ_1259_m12', 'TZ_1258_m12', 'TZ_1225_m12', 'TZ_1264_m12', 'TZ_1228_m12', 'TZ_1229_m12', 'TZ_1230_m12', 'TZ_1226_m12', 'TZ_1271_m12', 'TZ_1232_m12', 'TZ_1233_m12', 'TZ_1234_m12', 'TZ_1261_m12', 'TZ_1262_m12', 'TZ_1239_m12', 'TZ_1260_m12', 'TZ_1257_m12', 'TZ_1266_m12', 'TZ_1364_m6', 'TZ_0152_m18', 'TZ_0372', 'TZ_0075_m3', 'TZ_0271_m3', 'TZ_0226_m24', 'TZ_0155_m18', 'TZ_1589_m3', 'TZ_0331_m5', 'TZ_0183_m6', 'TZ_1652_m24', 'TZ_0037_m12', 'TZ_0400_m9', 'TZ_0079_m6', 'TZ_0248_m24', 'TZ_0963_m12', 'TZ_1622_m24', 'TZ_0173_m9', 'TZ_0077_m6', 'TZ_0332_m4', 'TZ_0140_m4', 'TZ_0334_m4', 'TZ_0333_m4', 'TZ_0141_m4', 'TZ_1750_m24', 'TZ_0052_m15', 'TZ_0076_m5', 'TZ_1510_m18', 'TZ_1557_m1', 'TZ_1525_m1', 'TZ_0132_m1', 'TZ_0371', 'TZ_0033_m9', 'TZ_0373', 'TZ_0143_m4', 'TZ_0269_m3', 'TZ_1269_m6', 'TZ_1237_m6', 'TZ_1381_m1', 'TZ_0329_m3', 'TZ_1429_m6', 'TZ_1398_m3', 'TZ_1512_m24', 'TZ_1560_m1', 'TZ_1528_m1', 'TZ_0250_m15', 'TZ_0036_m9', 'TZ_1336_m3', 'TZ_1461_m6', 'TZ_0247_m15', 'TZ_1512_m18', 'TZ_0079_m5', 'TZ_1656_m18', 'TZ_0053_m24', 'TZ_1512_m12', 'TZ_1576_m6', 'TZ_2016_T2_m24', 'TZ_0077_m5', 'TZ_1272_m6', 'TZ_0176_m15', 'TZ_1461_m18', 'TZ_1718_m24', 'TZ_1734_m24', 'TZ_0419_m12', 'TZ_0403_m6', 'TZ_1591_m3', 'TZ_1577_m3', 'TZ_1581_m3', 'TZ_1586_m3', 'TZ_1588_m3', 'TZ_1584_m3', 'TZ_1578_m3', 'TZ_1582_m3', 'TZ_1583_m3', 'TZ_1587_m3', 'TZ_1580_m3', 'TZ_1579_m3', 'TZ_1590_m3', 'TZ_1585_m3', 'TZ_1240_m6', 'TZ_0192_m1', 'TZ_0400_m8', 'TZ_1221_m12', 'TZ_0963_m9', 'TZ_0032_m6', 'TZ_0461_m6', 'TZ_1386_m6', 'TZ_1387_m6', 'TZ_1389_m6', 'TZ_1388_m6', 'TZ_1390_m6', 'TZ_1393_m6', 'TZ_1395_m6', 'TZ_1394_m6', 'TZ_1399_m6', 'TZ_1391_m6', 'TZ_1385_m6', 'TZ_1392_m6', 'TZ_0252_m18', 'TZ_0063_m18', 'TZ_0253_m18', 'TZ_0061_m18', 'TZ_0254_m18', 'TZ_0060_m18', 'TZ_0039_m9', 'TZ_0226_m18', 'TZ_0180_m3', 'TZ_0225_m24', 'TZ_0266_w3', 'TZ_0249_m24', 'TZ_0181_m3', 'TZ_1685_m24', 'TZ_0177_m18', 'TZ_0179_m15', 'TZ_1624_m18', 'TZ_0134_m2', 'TZ_0338_m18', 'TZ_0336_m18', 'TZ_0147_m18', 'TZ_0337_m18', 'TZ_0145_m18', 'TZ_0144_m18', 'TZ_1429_m18', 'TZ_1332_m6', 'TZ_0175_m6', 'TZ_0400_m7', 'TZ_0419_m11', 'TZ_0264_w3', 'TZ_0224_m18', 'TZ_1979_m6', 'TZ_0453_m24', 'TZ_0252_m15', 'TZ_0254_m15', 'TZ_0060_m15', 'TZ_0061_m15', 'TZ_0253_m15', 'TZ_0063_m15', 'TZ_0265_w3', 'TZ_0172_m6', 'TZ_0072_m2', 'TZ_0055_m18', 'TZ_0328_m3', 'TZ_0035_m6', 'TZ_1652_m18', 'TZ_1366_m6', 'TZ_0246_m6', 'TZ_0132_w4', 'TZ_0073_m2', 'TZ_0153_m18', 'TZ_1980_m18', 'TZ_1980_m12', 'TZ_1980_m24', 'TZ_0247_m12', 'TZ_1384_m18', 'TZ_1301_m24', 'TZ_0135_w4', 'TZ_0183_m5', 'TZ_0963_m6', 'TZ_0052_m12', 'TZ_0400_m6', 'TZ_0268_m2', 'TZ_0173_m6', 'TZ_0195_w4', 'TZ_1384_m12', 'TZ_0135_m2', 'TZ_0076_m4', 'TZ_0152_m15', 'TZ_0374', 'TZ_1317_m1', 'TZ_1620_m18', 'TZ_1328_m24', 'TZ_1359_m24', 'TZ_1325_m24', 'TZ_1321_m24', 'TZ_1367_m24', 'TZ_1323_m24', 'TZ_1322_m24', 'TZ_1327_m24', 'TZ_1324_m24', 'TZ_1363_m24', 'TZ_1329_m24', 'TZ_1326_m24', 'TZ_1358_m24', 'TZ_1361_m24', 'TZ_1362_m24', 'TZ_1330_m24', 'TZ_1331_m24', 'TZ_1355_m24', 'TZ_1335_m24', 'TZ_1357_m24', 'TZ_1353_m24', 'TZ_1354_m24', 'TZ_1360_m24', 'TZ_1356_m24', 'TZ_1654_m18', 'TZ_0155_m15', 'TZ_0225_m18', 'TZ_0249_m18', 'TZ_0269_m2', 'TZ_1622_m18', 'TZ_0033_m6', 'TZ_0133_w4', 'TZ_1519_m1', 'TZ_1545_m1', 'TZ_1547_m1', 'TZ_1524_m1', 'TZ_0961_m1', 'TZ_1518_m1', 'TZ_1548_m1', 'TZ_1520_m1', 'TZ_1522_m1', 'TZ_1521_m1', 'TZ_1553_m1', 'TZ_1981_m1', 'TZ_1549_m1', 'TZ_1526_m1', 'TZ_1517_m1', 'TZ_1513_m1', 'TZ_1552_m1', 'TZ_1515_m1', 'TZ_1555_m1', 'TZ_1516_m1', 'TZ_1556_m1', 'TZ_1514_m1', 'TZ_1554_m1', 'TZ_1984_m1', 'TZ_1559_m1', 'TZ_1558_m1', 'TZ_1546_m1', 'TZ_1523_m1', 'TZ_1527_m1', 'TZ_1550_m1', 'TZ_1551_m1', 'TZ_0177_m15', 'TZ_1382_m18', 'TZ_1544_m6', 'TZ_0991', 'TZ_2019_T2_m24', 'TZ_1461_m12', 'TZ_0990', 'TZ_1637_m6', 'TZ_0077_m4', 'TZ_0226_m15', 'TZ_0443_m24', 'TZ_0032_m5', 'TZ_1329_m18', 'TZ_1335_m18', 'TZ_1326_m18', 'TZ_1331_m18', 'TZ_1356_m18', 'TZ_1328_m18', 'TZ_1355_m18', 'TZ_1357_m18', 'TZ_1360_m18', 'TZ_1327_m18', 'TZ_1358_m18', 'TZ_1361_m18', 'TZ_1367_m18', 'TZ_1353_m18', 'TZ_1363_m18', 'TZ_1362_m18', 'TZ_1330_m18', 'TZ_1323_m18', 'TZ_1325_m18', 'TZ_1321_m18', 'TZ_1322_m18', 'TZ_1359_m18', 'TZ_1324_m18', 'TZ_1354_m18', 'TZ_0252_m12', 'TZ_0060_m12', 'TZ_0253_m12', 'TZ_0061_m12', 'TZ_0254_m12', 'TZ_0063_m12', 'TZ_1702_m24', 'TZ_0455_m6', 'TZ_1574_m12', 'TZ_1397_m1', 'TZ_0037_m9', 'TZ_0403_m5', 'TZ_1384_m24', 'TZ_0055_m15', 'TZ_0194_m2', 'TZ_1653_m6', 'TZ_0331_m4', 'TZ_0136_m1', 'TZ_0115_m24', 'TZ_0112_m24', 'TZ_0172_m5', 'TZ_0191_m24', 'TZ_1270_m6', 'TZ_1238_m6', 'TZ_0056_m24', 'TZ_1334_m3', 'TZ_0188_m24', 'TZ_0189_m2

In [45]:
gc.collect()

0

In [46]:
from ScoreCard.creat_report import Report
length = 300
for i in range(0,(len(ft_lst) // length) + 1):
    start, end = i * length, min((i + 1) * length, len(ft_lst))
    print(start, ' - ', end)
    report = Report(data_all1[ft_lst[start:end] + ex_lst], ex_lst, 'label', FILE_PATH + str(i) + '_')
#     key_value, bins_detail = report.iv_ks_psi()
#     key_value, bins_detail = report.iv_ks_psi_chi2()
    key_value, bins_detail = report.iv_ks_psi_chi2_missing_quantile()
    del report,key_value,bins_detail

0  -  300
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
300  -  600
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
600  -  900
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
900  -  1200
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
1200  -  1500
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
1500  -  1800
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存
1800  -  2000
正在计算IV......
正在计算CHI2......
正在计算COVER RATE......
正在计算QUANTILE......
正在保存结果......
已保存

In [47]:
import os
files_key_value, files_bins_detail = [], []
for root, dirs, files in os.walk(FILE_PATH[:-1]): 
    for file in files:
        if '_bins_detail' in file:
            files_bins_detail.append(pd.read_excel(root +'/'+ file))
        elif 'iv_ipt_psi_chi2_missing' in file:
            files_key_value.append(pd.read_excel(root +'/'+ file))
            
key_value = pd.concat(files_key_value)
bins_detail = pd.concat(files_bins_detail)

bins_detail.to_excel(FILE_PATH + 'bins_detail.xlsx')
key_value.to_excel(FILE_PATH + 'key_value.xlsx')

In [48]:
key_value.sort_values(by='iv_bin_train', ascending=False)

,Unnamed: 0,var_names,ks,iv_bin_train,iv_bin_valid,iv_bin_oot,iv_bin_total,psi_tv_bin,psi_to_bin,psi_tvo_bin,...,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99,max
24,24,TZ_1381_m12,0.0,0.038564,0.036497,0.008511,0.032865,1.108571e-06,0.015145,0.015099,...,-1.0,-1.0,-1.0,-1.0,2.0,8.0,20.0,25.000000,38.000000,56.000000
227,227,TZ_1381_m24,0.0,0.037503,0.038238,0.011769,0.032295,1.339798e-05,0.009230,0.009091,...,-1.0,-1.0,-1.0,0.0,4.0,15.0,23.0,32.000000,39.000000,56.000000
206,206,TZ_1381_m18,0.0,0.037476,0.036241,0.012913,0.032099,1.957952e-05,0.015288,0.015252,...,-1.0,-1.0,-1.0,0.0,3.0,12.0,22.0,29.000000,38.000000,56.000000
202,202,TZ_0264_m24,0.0,0.036290,0.035740,0.008300,0.029613,3.680588e-06,0.032093,0.032057,...,-1.0,1.0,4.0,10.0,20.0,23.0,33.0,38.000000,44.000000,56.000000
204,204,TZ_0264_m12,0.0,0.035987,0.036751,0.011556,0.029685,1.010345e-05,0.042098,0.042134,...,-1.0,0.0,2.0,5.0,11.0,20.0,24.0,31.000000,39.000000,56.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,84,TZ_0455_m3,0.0,0.003567,0.004010,0.003825,0.003395,1.111656e-07,0.008236,0.008251,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,3.000000,17.000000,56.000000
41,41,TZ_0288_m4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.000000,2.000000,18.000000
40,40,TZ_0290_m4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.000000,2.000000,4.000000
174,174,TZ_0143_m3,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.333333,110.333336
43,43,TZ_0289_m4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.000000,1.000000,4.000000

In [49]:
bins_detail.sort_values(by='total_iv', ascending=False)

,Unnamed: 0,Unnamed: 1,variable,value,bin,count,count_distr,good,goodprob,bad,badprob,iv,total_iv,ks,total_ks,woe
1,NaN,1,TZ_1381_m12,1,"[0.5, 4.5)",80579,0.100251,76879,0.100260,3700,0.100049,4.477439e-07,0.038564,0.073029,0.073241,-0.002114
0,TZ_1381_m12,0,TZ_1381_m12,0,"[-inf, 0.5)",534706,0.665243,507520,0.661874,27186,0.735114,7.686742e-03,0.038564,0.073241,0.073241,0.104952
2,NaN,2,TZ_1381_m12,2,"[4.5, 17.5)",80474,0.100120,77495,0.101064,2979,0.080553,4.652737e-03,0.038564,0.052518,0.073241,-0.226840
3,NaN,3,TZ_1381_m12,3,"[17.5, 21.5)",42969,0.053459,41603,0.054256,1366,0.036937,6.659137e-03,0.038564,0.035199,0.073241,-0.384500
4,NaN,4,TZ_1381_m12,4,"[21.5, inf)",65047,0.080927,63296,0.082546,1751,0.047347,1.956537e-02,0.038564,0.000000,0.073241,-0.555850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,TZ_0455_m3,0,TZ_0455_m3,0,"[-inf, -0.5)",666622,0.829364,635709,0.829049,30913,0.835893,5.626855e-05,0.003567,0.006844,0.012769,0.008221
581,TZ_0289_m4,0,TZ_0289_m4,0,"[-inf, inf)",803775,1.000000,766793,1.000000,36982,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
580,TZ_0288_m4,0,TZ_0288_m4,0,"[-inf, inf)",803775,1.000000,766793,1.000000,36982,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
579,TZ_0290_m4,0,TZ_0290_m4,0,"[-inf, inf)",803775,1.000000,766793,1.000000,36982,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
140,TZ_0143_m3,0,TZ_0143_m3,0,"[-inf, inf)",803775,1.000000,766793,1.000000,36982,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000

In [50]:
%reset -f